shared-version = true
pre-release-commit-message = "Release v{{version}}"
tag-message = "Release v{{version}}"
tag-name = "v{{version}}"
pre-release-replacements = [
    { file = "../CHANGELOG.md", search = "Unreleased", replace = "{{version}}" },
    { file = "../CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}" },
    { file = "../CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly = 1 },
]
