[package]
name = "opener-bin"
version = "0.1.0"
authors = ["Brian Bowman <seeker14491@gmail.com>"]
edition = "2018"

[dependencies]
opener = { path = "../opener" }
structopt = "0.3.1"

[features]
reveal = ["opener/reveal"]
